/**
 * Created by feichongzheng on 17/9/25.
 */
export const FIND_USER_FOR_PAGE = 'USER/FINDFORPAGE';
export const FIND_USER_FOR_PAGE_FETCH = 'USER/FINDFORPAGEFETCH';
export const FIND_USER_FOR_PAGE_SUCCESS = 'USER/FINDFORPAGESUCCESS';
export const FIND_USER_FOR_PAGE_ERROR = 'USER/FINDFORPAGEERROR';
